<?xml version="1.0" encoding="utf-8"?><Database Name="ColonyDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=colonydb.czjxltdxzhsv.ap-northeast-1.rds.amazonaws.com,1433;Initial Catalog=ColonyDB;User ID=colonydbadmin;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ColonyDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GroupTable" Member="GroupTables">
    <Type Name="GroupTable">
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(3500) NOT NULL" CanBeNull="false" />
      <Column Name="IsLogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdateUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DeleteUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroupTable" Member="UserGroupTables">
    <Type Name="UserGroupTable">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupId01" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupId02" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId03" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId04" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId05" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId06" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId07" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId08" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId09" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId10" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId11" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId12" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId13" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId14" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId15" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId16" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId17" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId18" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId19" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId20" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId21" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId22" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId23" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId24" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId25" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId26" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId27" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId28" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId29" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId30" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId31" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId32" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId33" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId34" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId35" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId36" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId37" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId38" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId39" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId40" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId41" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId42" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId43" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId44" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId45" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId46" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId47" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId48" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId49" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GroupId50" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsLogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdateUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DeleteUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTable" Member="UserTables">
    <Type Name="UserTable">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="MailAddress" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="IsLogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UpdateUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DeleteUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
</Database>