//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 名前空間 http://colonywebappdb.azurewebsites.net/ の要素名 HelloWorldResult が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/HelloWorld", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.HelloWorldResponse HelloWorld(ConsoleApplication1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ConsoleApplication1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/CreateUserId", ReplyAction="*")]
        System.Guid CreateUserId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/CreateUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> CreateUserIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/CreateGroupId", ReplyAction="*")]
        System.Guid CreateGroupId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/CreateGroupId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> CreateGroupIdAsync();
        
        // CODEGEN: 名前空間 http://colonywebappdb.azurewebsites.net/ の要素名 nickName が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/CreateUser", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.CreateUserResponse CreateUser(ConsoleApplication1.ServiceReference1.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CreateUserResponse> CreateUserAsync(ConsoleApplication1.ServiceReference1.CreateUserRequest request);
        
        // CODEGEN: 名前空間 http://colonywebappdb.azurewebsites.net/ の要素名 nickName が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsUser", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.IsExistsUserResponse IsExistsUser(ConsoleApplication1.ServiceReference1.IsExistsUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsUserResponse> IsExistsUserAsync(ConsoleApplication1.ServiceReference1.IsExistsUserRequest request);
        
        // CODEGEN: 名前空間 http://colonywebappdb.azurewebsites.net/ の要素名 groupName が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsGroup", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.IsExistsGroupResponse IsExistsGroup(ConsoleApplication1.ServiceReference1.IsExistsGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsGroupResponse> IsExistsGroupAsync(ConsoleApplication1.ServiceReference1.IsExistsGroupRequest request);
        
        // CODEGEN: 名前空間 http://colonywebappdb.azurewebsites.net/ の要素名 nickname が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsUserGroupChainByName", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponse IsExistsUserGroupChainByName(ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsUserGroupChainByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponse> IsExistsUserGroupChainByNameAsync(ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsUserGroupChainById", ReplyAction="*")]
        bool IsExistsUserGroupChainById(System.Guid userId, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/IsExistsUserGroupChainById", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsExistsUserGroupChainByIdAsync(System.Guid userId, System.Guid groupId);
        
        // CODEGEN: 名前空間 http://colonywebappdb.azurewebsites.net/ の要素名 oldNickname が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/ModifyNickName", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.ModifyNickNameResponse ModifyNickName(ConsoleApplication1.ServiceReference1.ModifyNickNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://colonywebappdb.azurewebsites.net/ModifyNickName", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ModifyNickNameResponse> ModifyNickNameAsync(ConsoleApplication1.ServiceReference1.ModifyNickNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApplication1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApplication1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(ConsoleApplication1.ServiceReference1.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string groupName;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string nickName, string mailAddress, string groupName) {
            this.nickName = nickName;
            this.mailAddress = mailAddress;
            this.groupName = groupName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(ConsoleApplication1.ServiceReference1.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(bool CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsExistsUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsExistsUser", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.IsExistsUserRequestBody Body;
        
        public IsExistsUserRequest() {
        }
        
        public IsExistsUserRequest(ConsoleApplication1.ServiceReference1.IsExistsUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class IsExistsUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mailAddress;
        
        public IsExistsUserRequestBody() {
        }
        
        public IsExistsUserRequestBody(string nickName, string mailAddress) {
            this.nickName = nickName;
            this.mailAddress = mailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsExistsUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsExistsUserResponse", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.IsExistsUserResponseBody Body;
        
        public IsExistsUserResponse() {
        }
        
        public IsExistsUserResponse(ConsoleApplication1.ServiceReference1.IsExistsUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class IsExistsUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsExistsUserResult;
        
        public IsExistsUserResponseBody() {
        }
        
        public IsExistsUserResponseBody(bool IsExistsUserResult) {
            this.IsExistsUserResult = IsExistsUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsExistsGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsExistsGroup", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.IsExistsGroupRequestBody Body;
        
        public IsExistsGroupRequest() {
        }
        
        public IsExistsGroupRequest(ConsoleApplication1.ServiceReference1.IsExistsGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class IsExistsGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupName;
        
        public IsExistsGroupRequestBody() {
        }
        
        public IsExistsGroupRequestBody(string groupName) {
            this.groupName = groupName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsExistsGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsExistsGroupResponse", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.IsExistsGroupResponseBody Body;
        
        public IsExistsGroupResponse() {
        }
        
        public IsExistsGroupResponse(ConsoleApplication1.ServiceReference1.IsExistsGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class IsExistsGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsExistsGroupResult;
        
        public IsExistsGroupResponseBody() {
        }
        
        public IsExistsGroupResponseBody(bool IsExistsGroupResult) {
            this.IsExistsGroupResult = IsExistsGroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsExistsUserGroupChainByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsExistsUserGroupChainByName", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequestBody Body;
        
        public IsExistsUserGroupChainByNameRequest() {
        }
        
        public IsExistsUserGroupChainByNameRequest(ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class IsExistsUserGroupChainByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string groupName01;
        
        public IsExistsUserGroupChainByNameRequestBody() {
        }
        
        public IsExistsUserGroupChainByNameRequestBody(string nickname, string groupName01) {
            this.nickname = nickname;
            this.groupName01 = groupName01;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsExistsUserGroupChainByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsExistsUserGroupChainByNameResponse", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponseBody Body;
        
        public IsExistsUserGroupChainByNameResponse() {
        }
        
        public IsExistsUserGroupChainByNameResponse(ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class IsExistsUserGroupChainByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsExistsUserGroupChainByNameResult;
        
        public IsExistsUserGroupChainByNameResponseBody() {
        }
        
        public IsExistsUserGroupChainByNameResponseBody(bool IsExistsUserGroupChainByNameResult) {
            this.IsExistsUserGroupChainByNameResult = IsExistsUserGroupChainByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyNickNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyNickName", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.ModifyNickNameRequestBody Body;
        
        public ModifyNickNameRequest() {
        }
        
        public ModifyNickNameRequest(ConsoleApplication1.ServiceReference1.ModifyNickNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class ModifyNickNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldNickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newNickname;
        
        public ModifyNickNameRequestBody() {
        }
        
        public ModifyNickNameRequestBody(System.Guid userId, string oldNickname, string newNickname) {
            this.userId = userId;
            this.oldNickname = oldNickname;
            this.newNickname = newNickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyNickNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyNickNameResponse", Namespace="http://colonywebappdb.azurewebsites.net/", Order=0)]
        public ConsoleApplication1.ServiceReference1.ModifyNickNameResponseBody Body;
        
        public ModifyNickNameResponse() {
        }
        
        public ModifyNickNameResponse(ConsoleApplication1.ServiceReference1.ModifyNickNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://colonywebappdb.azurewebsites.net/")]
    public partial class ModifyNickNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModifyNickNameResult;
        
        public ModifyNickNameResponseBody() {
        }
        
        public ModifyNickNameResponseBody(bool ModifyNickNameResult) {
            this.ModifyNickNameResult = ModifyNickNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.WebService1Soap>, ConsoleApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.HelloWorldResponse ConsoleApplication1.ServiceReference1.WebService1Soap.HelloWorld(ConsoleApplication1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApplication1.ServiceReference1.HelloWorldRequest inValue = new ConsoleApplication1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.HelloWorldRequestBody();
            ConsoleApplication1.ServiceReference1.HelloWorldResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.HelloWorldResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.HelloWorldAsync(ConsoleApplication1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApplication1.ServiceReference1.HelloWorldRequest inValue = new ConsoleApplication1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.HelloWorldRequestBody();
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public System.Guid CreateUserId() {
            return base.Channel.CreateUserId();
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateUserIdAsync() {
            return base.Channel.CreateUserIdAsync();
        }
        
        public System.Guid CreateGroupId() {
            return base.Channel.CreateGroupId();
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateGroupIdAsync() {
            return base.Channel.CreateGroupIdAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.CreateUserResponse ConsoleApplication1.ServiceReference1.WebService1Soap.CreateUser(ConsoleApplication1.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public bool CreateUser(string nickName, string mailAddress, string groupName) {
            ConsoleApplication1.ServiceReference1.CreateUserRequest inValue = new ConsoleApplication1.ServiceReference1.CreateUserRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.CreateUserRequestBody();
            inValue.Body.nickName = nickName;
            inValue.Body.mailAddress = mailAddress;
            inValue.Body.groupName = groupName;
            ConsoleApplication1.ServiceReference1.CreateUserResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CreateUserResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.CreateUserAsync(ConsoleApplication1.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CreateUserResponse> CreateUserAsync(string nickName, string mailAddress, string groupName) {
            ConsoleApplication1.ServiceReference1.CreateUserRequest inValue = new ConsoleApplication1.ServiceReference1.CreateUserRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.CreateUserRequestBody();
            inValue.Body.nickName = nickName;
            inValue.Body.mailAddress = mailAddress;
            inValue.Body.groupName = groupName;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.IsExistsUserResponse ConsoleApplication1.ServiceReference1.WebService1Soap.IsExistsUser(ConsoleApplication1.ServiceReference1.IsExistsUserRequest request) {
            return base.Channel.IsExistsUser(request);
        }
        
        public bool IsExistsUser(string nickName, string mailAddress) {
            ConsoleApplication1.ServiceReference1.IsExistsUserRequest inValue = new ConsoleApplication1.ServiceReference1.IsExistsUserRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.IsExistsUserRequestBody();
            inValue.Body.nickName = nickName;
            inValue.Body.mailAddress = mailAddress;
            ConsoleApplication1.ServiceReference1.IsExistsUserResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).IsExistsUser(inValue);
            return retVal.Body.IsExistsUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsUserResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.IsExistsUserAsync(ConsoleApplication1.ServiceReference1.IsExistsUserRequest request) {
            return base.Channel.IsExistsUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsUserResponse> IsExistsUserAsync(string nickName, string mailAddress) {
            ConsoleApplication1.ServiceReference1.IsExistsUserRequest inValue = new ConsoleApplication1.ServiceReference1.IsExistsUserRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.IsExistsUserRequestBody();
            inValue.Body.nickName = nickName;
            inValue.Body.mailAddress = mailAddress;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).IsExistsUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.IsExistsGroupResponse ConsoleApplication1.ServiceReference1.WebService1Soap.IsExistsGroup(ConsoleApplication1.ServiceReference1.IsExistsGroupRequest request) {
            return base.Channel.IsExistsGroup(request);
        }
        
        public bool IsExistsGroup(string groupName) {
            ConsoleApplication1.ServiceReference1.IsExistsGroupRequest inValue = new ConsoleApplication1.ServiceReference1.IsExistsGroupRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.IsExistsGroupRequestBody();
            inValue.Body.groupName = groupName;
            ConsoleApplication1.ServiceReference1.IsExistsGroupResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).IsExistsGroup(inValue);
            return retVal.Body.IsExistsGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsGroupResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.IsExistsGroupAsync(ConsoleApplication1.ServiceReference1.IsExistsGroupRequest request) {
            return base.Channel.IsExistsGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsGroupResponse> IsExistsGroupAsync(string groupName) {
            ConsoleApplication1.ServiceReference1.IsExistsGroupRequest inValue = new ConsoleApplication1.ServiceReference1.IsExistsGroupRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.IsExistsGroupRequestBody();
            inValue.Body.groupName = groupName;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).IsExistsGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponse ConsoleApplication1.ServiceReference1.WebService1Soap.IsExistsUserGroupChainByName(ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest request) {
            return base.Channel.IsExistsUserGroupChainByName(request);
        }
        
        public bool IsExistsUserGroupChainByName(string nickname, string groupName01) {
            ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest inValue = new ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.groupName01 = groupName01;
            ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).IsExistsUserGroupChainByName(inValue);
            return retVal.Body.IsExistsUserGroupChainByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.IsExistsUserGroupChainByNameAsync(ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest request) {
            return base.Channel.IsExistsUserGroupChainByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameResponse> IsExistsUserGroupChainByNameAsync(string nickname, string groupName01) {
            ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest inValue = new ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.IsExistsUserGroupChainByNameRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.groupName01 = groupName01;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).IsExistsUserGroupChainByNameAsync(inValue);
        }
        
        public bool IsExistsUserGroupChainById(System.Guid userId, System.Guid groupId) {
            return base.Channel.IsExistsUserGroupChainById(userId, groupId);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsUserGroupChainByIdAsync(System.Guid userId, System.Guid groupId) {
            return base.Channel.IsExistsUserGroupChainByIdAsync(userId, groupId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.ModifyNickNameResponse ConsoleApplication1.ServiceReference1.WebService1Soap.ModifyNickName(ConsoleApplication1.ServiceReference1.ModifyNickNameRequest request) {
            return base.Channel.ModifyNickName(request);
        }
        
        public bool ModifyNickName(System.Guid userId, string oldNickname, string newNickname) {
            ConsoleApplication1.ServiceReference1.ModifyNickNameRequest inValue = new ConsoleApplication1.ServiceReference1.ModifyNickNameRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.ModifyNickNameRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.oldNickname = oldNickname;
            inValue.Body.newNickname = newNickname;
            ConsoleApplication1.ServiceReference1.ModifyNickNameResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).ModifyNickName(inValue);
            return retVal.Body.ModifyNickNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ModifyNickNameResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.ModifyNickNameAsync(ConsoleApplication1.ServiceReference1.ModifyNickNameRequest request) {
            return base.Channel.ModifyNickNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ModifyNickNameResponse> ModifyNickNameAsync(System.Guid userId, string oldNickname, string newNickname) {
            ConsoleApplication1.ServiceReference1.ModifyNickNameRequest inValue = new ConsoleApplication1.ServiceReference1.ModifyNickNameRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.ModifyNickNameRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.oldNickname = oldNickname;
            inValue.Body.newNickname = newNickname;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).ModifyNickNameAsync(inValue);
        }
    }
}
