#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ColonyDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertUserTable(UserTable instance);
    partial void UpdateUserTable(UserTable instance);
    partial void DeleteUserTable(UserTable instance);
    partial void InsertGroupTable(GroupTable instance);
    partial void UpdateGroupTable(GroupTable instance);
    partial void DeleteGroupTable(GroupTable instance);
    partial void InsertUserGroupTable(UserGroupTable instance);
    partial void UpdateUserGroupTable(UserGroupTable instance);
    partial void DeleteUserGroupTable(UserGroupTable instance);
    partial void InsertTargetDataTable(TargetDataTable instance);
    partial void UpdateTargetDataTable(TargetDataTable instance);
    partial void DeleteTargetDataTable(TargetDataTable instance);
    partial void InsertUserTargetDataTable(UserTargetDataTable instance);
    partial void UpdateUserTargetDataTable(UserTargetDataTable instance);
    partial void DeleteUserTargetDataTable(UserTargetDataTable instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ColonyDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserTable> UserTables
		{
			get
			{
				return this.GetTable<UserTable>();
			}
		}
		
		public System.Data.Linq.Table<GroupTable> GroupTables
		{
			get
			{
				return this.GetTable<GroupTable>();
			}
		}
		
		public System.Data.Linq.Table<UserGroupTable> UserGroupTables
		{
			get
			{
				return this.GetTable<UserGroupTable>();
			}
		}
		
		public System.Data.Linq.Table<TargetDataTable> TargetDataTable
		{
			get
			{
				return this.GetTable<TargetDataTable>();
			}
		}
		
		public System.Data.Linq.Table<UserTargetDataTable> UserTargetDataTable
		{
			get
			{
				return this.GetTable<UserTargetDataTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTable")]
	public partial class UserTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Nickname;
		
		private string _MailAddress;
		
		private bool _IsLogicalDelete;
		
		private System.Nullable<System.Guid> _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.Guid> _UpdateUser;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.Guid> _DeleteUser;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private EntitySet<UserGroupTable> _UserGroupTables;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNicknameChanging(string value);
    partial void OnNicknameChanged();
    partial void OnMailAddressChanging(string value);
    partial void OnMailAddressChanged();
    partial void OnIsLogicalDeleteChanging(bool value);
    partial void OnIsLogicalDeleteChanged();
    partial void OnCreateUserChanging(System.Nullable<System.Guid> value);
    partial void OnCreateUserChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateUserChanging(System.Nullable<System.Guid> value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeleteUserChanging(System.Nullable<System.Guid> value);
    partial void OnDeleteUserChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    #endregion
		
		public UserTable()
		{
			this._UserGroupTables = new EntitySet<UserGroupTable>(new Action<UserGroupTable>(this.attach_UserGroupTables), new Action<UserGroupTable>(this.detach_UserGroupTables));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this.OnNicknameChanging(value);
					this.SendPropertyChanging();
					this._Nickname = value;
					this.SendPropertyChanged("Nickname");
					this.OnNicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailAddress", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string MailAddress
		{
			get
			{
				return this._MailAddress;
			}
			set
			{
				if ((this._MailAddress != value))
				{
					this.OnMailAddressChanging(value);
					this.SendPropertyChanging();
					this._MailAddress = value;
					this.SendPropertyChanged("MailAddress");
					this.OnMailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogicalDelete", DbType="Bit NOT NULL")]
		public bool IsLogicalDelete
		{
			get
			{
				return this._IsLogicalDelete;
			}
			set
			{
				if ((this._IsLogicalDelete != value))
				{
					this.OnIsLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsLogicalDelete = value;
					this.SendPropertyChanged("IsLogicalDelete");
					this.OnIsLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this.OnCreateUserChanging(value);
					this.SendPropertyChanging();
					this._CreateUser = value;
					this.SendPropertyChanged("CreateUser");
					this.OnCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeleteUser
		{
			get
			{
				return this._DeleteUser;
			}
			set
			{
				if ((this._DeleteUser != value))
				{
					this.OnDeleteUserChanging(value);
					this.SendPropertyChanging();
					this._DeleteUser = value;
					this.SendPropertyChanged("DeleteUser");
					this.OnDeleteUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTable_UserGroupTable", Storage="_UserGroupTables", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<UserGroupTable> UserGroupTables
		{
			get
			{
				return this._UserGroupTables;
			}
			set
			{
				this._UserGroupTables.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserGroupTables(UserGroupTable entity)
		{
			this.SendPropertyChanging();
			entity.UserTable = this;
		}
		
		private void detach_UserGroupTables(UserGroupTable entity)
		{
			this.SendPropertyChanging();
			entity.UserTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GroupTable")]
	public partial class GroupTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _GroupId;
		
		private string _GroupName;
		
		private bool _IsLogicalDelete;
		
		private System.Nullable<System.Guid> _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.Guid> _UpdateUser;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.Guid> _DeleteUser;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private EntityRef<UserGroupTable> _UserGroupTable;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIdChanging(System.Guid value);
    partial void OnGroupIdChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnIsLogicalDeleteChanging(bool value);
    partial void OnIsLogicalDeleteChanged();
    partial void OnCreateUserChanging(System.Nullable<System.Guid> value);
    partial void OnCreateUserChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateUserChanging(System.Nullable<System.Guid> value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeleteUserChanging(System.Nullable<System.Guid> value);
    partial void OnDeleteUserChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    #endregion
		
		public GroupTable()
		{
			this._UserGroupTable = default(EntityRef<UserGroupTable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._UserGroupTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(3500) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogicalDelete", DbType="Bit NOT NULL")]
		public bool IsLogicalDelete
		{
			get
			{
				return this._IsLogicalDelete;
			}
			set
			{
				if ((this._IsLogicalDelete != value))
				{
					this.OnIsLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsLogicalDelete = value;
					this.SendPropertyChanged("IsLogicalDelete");
					this.OnIsLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this.OnCreateUserChanging(value);
					this.SendPropertyChanging();
					this._CreateUser = value;
					this.SendPropertyChanged("CreateUser");
					this.OnCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeleteUser
		{
			get
			{
				return this._DeleteUser;
			}
			set
			{
				if ((this._DeleteUser != value))
				{
					this.OnDeleteUserChanging(value);
					this.SendPropertyChanging();
					this._DeleteUser = value;
					this.SendPropertyChanged("DeleteUser");
					this.OnDeleteUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserGroupTable_GroupTable", Storage="_UserGroupTable", ThisKey="GroupId", OtherKey="GroupId01", IsForeignKey=true)]
		public UserGroupTable UserGroupTable
		{
			get
			{
				return this._UserGroupTable.Entity;
			}
			set
			{
				UserGroupTable previousValue = this._UserGroupTable.Entity;
				if (((previousValue != value) 
							|| (this._UserGroupTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserGroupTable.Entity = null;
						previousValue.GroupTables.Remove(this);
					}
					this._UserGroupTable.Entity = value;
					if ((value != null))
					{
						value.GroupTables.Add(this);
						this._GroupId = value.GroupId01;
					}
					else
					{
						this._GroupId = default(System.Guid);
					}
					this.SendPropertyChanged("UserGroupTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserGroupTable")]
	public partial class UserGroupTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserId;
		
		private System.Guid _GroupId01;
		
		private System.Nullable<System.Guid> _GroupId02;
		
		private System.Nullable<System.Guid> _GroupId03;
		
		private System.Nullable<System.Guid> _GroupId04;
		
		private System.Nullable<System.Guid> _GroupId05;
		
		private System.Nullable<System.Guid> _GroupId06;
		
		private System.Nullable<System.Guid> _GroupId07;
		
		private System.Nullable<System.Guid> _GroupId08;
		
		private System.Nullable<System.Guid> _GroupId09;
		
		private System.Nullable<System.Guid> _GroupId10;
		
		private System.Nullable<System.Guid> _GroupId11;
		
		private System.Nullable<System.Guid> _GroupId12;
		
		private System.Nullable<System.Guid> _GroupId13;
		
		private System.Nullable<System.Guid> _GroupId14;
		
		private System.Nullable<System.Guid> _GroupId15;
		
		private System.Nullable<System.Guid> _GroupId16;
		
		private System.Nullable<System.Guid> _GroupId17;
		
		private System.Nullable<System.Guid> _GroupId18;
		
		private System.Nullable<System.Guid> _GroupId19;
		
		private System.Nullable<System.Guid> _GroupId20;
		
		private System.Nullable<System.Guid> _GroupId21;
		
		private System.Nullable<System.Guid> _GroupId22;
		
		private System.Nullable<System.Guid> _GroupId23;
		
		private System.Nullable<System.Guid> _GroupId24;
		
		private System.Nullable<System.Guid> _GroupId25;
		
		private System.Nullable<System.Guid> _GroupId26;
		
		private System.Nullable<System.Guid> _GroupId27;
		
		private System.Nullable<System.Guid> _GroupId28;
		
		private System.Nullable<System.Guid> _GroupId29;
		
		private System.Nullable<System.Guid> _GroupId30;
		
		private System.Nullable<System.Guid> _GroupId31;
		
		private System.Nullable<System.Guid> _GroupId32;
		
		private System.Nullable<System.Guid> _GroupId33;
		
		private System.Nullable<System.Guid> _GroupId34;
		
		private System.Nullable<System.Guid> _GroupId35;
		
		private System.Nullable<System.Guid> _GroupId36;
		
		private System.Nullable<System.Guid> _GroupId37;
		
		private System.Nullable<System.Guid> _GroupId38;
		
		private System.Nullable<System.Guid> _GroupId39;
		
		private System.Nullable<System.Guid> _GroupId40;
		
		private System.Nullable<System.Guid> _GroupId41;
		
		private System.Nullable<System.Guid> _GroupId42;
		
		private System.Nullable<System.Guid> _GroupId43;
		
		private System.Nullable<System.Guid> _GroupId44;
		
		private System.Nullable<System.Guid> _GroupId45;
		
		private System.Nullable<System.Guid> _GroupId46;
		
		private System.Nullable<System.Guid> _GroupId47;
		
		private System.Nullable<System.Guid> _GroupId48;
		
		private System.Nullable<System.Guid> _GroupId49;
		
		private System.Nullable<System.Guid> _GroupId50;
		
		private bool _IsLogicalDelete;
		
		private System.Nullable<System.Guid> _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.Guid> _UpdateUser;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.Guid> _DeleteUser;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private EntitySet<GroupTable> _GroupTables;
		
		private EntityRef<UserTable> _UserTable;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnGroupId01Changing(System.Guid value);
    partial void OnGroupId01Changed();
    partial void OnGroupId02Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId02Changed();
    partial void OnGroupId03Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId03Changed();
    partial void OnGroupId04Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId04Changed();
    partial void OnGroupId05Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId05Changed();
    partial void OnGroupId06Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId06Changed();
    partial void OnGroupId07Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId07Changed();
    partial void OnGroupId08Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId08Changed();
    partial void OnGroupId09Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId09Changed();
    partial void OnGroupId10Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId10Changed();
    partial void OnGroupId11Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId11Changed();
    partial void OnGroupId12Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId12Changed();
    partial void OnGroupId13Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId13Changed();
    partial void OnGroupId14Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId14Changed();
    partial void OnGroupId15Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId15Changed();
    partial void OnGroupId16Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId16Changed();
    partial void OnGroupId17Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId17Changed();
    partial void OnGroupId18Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId18Changed();
    partial void OnGroupId19Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId19Changed();
    partial void OnGroupId20Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId20Changed();
    partial void OnGroupId21Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId21Changed();
    partial void OnGroupId22Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId22Changed();
    partial void OnGroupId23Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId23Changed();
    partial void OnGroupId24Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId24Changed();
    partial void OnGroupId25Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId25Changed();
    partial void OnGroupId26Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId26Changed();
    partial void OnGroupId27Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId27Changed();
    partial void OnGroupId28Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId28Changed();
    partial void OnGroupId29Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId29Changed();
    partial void OnGroupId30Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId30Changed();
    partial void OnGroupId31Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId31Changed();
    partial void OnGroupId32Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId32Changed();
    partial void OnGroupId33Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId33Changed();
    partial void OnGroupId34Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId34Changed();
    partial void OnGroupId35Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId35Changed();
    partial void OnGroupId36Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId36Changed();
    partial void OnGroupId37Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId37Changed();
    partial void OnGroupId38Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId38Changed();
    partial void OnGroupId39Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId39Changed();
    partial void OnGroupId40Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId40Changed();
    partial void OnGroupId41Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId41Changed();
    partial void OnGroupId42Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId42Changed();
    partial void OnGroupId43Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId43Changed();
    partial void OnGroupId44Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId44Changed();
    partial void OnGroupId45Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId45Changed();
    partial void OnGroupId46Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId46Changed();
    partial void OnGroupId47Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId47Changed();
    partial void OnGroupId48Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId48Changed();
    partial void OnGroupId49Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId49Changed();
    partial void OnGroupId50Changing(System.Nullable<System.Guid> value);
    partial void OnGroupId50Changed();
    partial void OnIsLogicalDeleteChanging(bool value);
    partial void OnIsLogicalDeleteChanged();
    partial void OnCreateUserChanging(System.Nullable<System.Guid> value);
    partial void OnCreateUserChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateUserChanging(System.Nullable<System.Guid> value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeleteUserChanging(System.Nullable<System.Guid> value);
    partial void OnDeleteUserChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    #endregion
		
		public UserGroupTable()
		{
			this._GroupTables = new EntitySet<GroupTable>(new Action<GroupTable>(this.attach_GroupTables), new Action<GroupTable>(this.detach_GroupTables));
			this._UserTable = default(EntityRef<UserTable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._UserTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId01", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GroupId01
		{
			get
			{
				return this._GroupId01;
			}
			set
			{
				if ((this._GroupId01 != value))
				{
					this.OnGroupId01Changing(value);
					this.SendPropertyChanging();
					this._GroupId01 = value;
					this.SendPropertyChanged("GroupId01");
					this.OnGroupId01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId02", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId02
		{
			get
			{
				return this._GroupId02;
			}
			set
			{
				if ((this._GroupId02 != value))
				{
					this.OnGroupId02Changing(value);
					this.SendPropertyChanging();
					this._GroupId02 = value;
					this.SendPropertyChanged("GroupId02");
					this.OnGroupId02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId03", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId03
		{
			get
			{
				return this._GroupId03;
			}
			set
			{
				if ((this._GroupId03 != value))
				{
					this.OnGroupId03Changing(value);
					this.SendPropertyChanging();
					this._GroupId03 = value;
					this.SendPropertyChanged("GroupId03");
					this.OnGroupId03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId04", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId04
		{
			get
			{
				return this._GroupId04;
			}
			set
			{
				if ((this._GroupId04 != value))
				{
					this.OnGroupId04Changing(value);
					this.SendPropertyChanging();
					this._GroupId04 = value;
					this.SendPropertyChanged("GroupId04");
					this.OnGroupId04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId05", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId05
		{
			get
			{
				return this._GroupId05;
			}
			set
			{
				if ((this._GroupId05 != value))
				{
					this.OnGroupId05Changing(value);
					this.SendPropertyChanging();
					this._GroupId05 = value;
					this.SendPropertyChanged("GroupId05");
					this.OnGroupId05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId06", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId06
		{
			get
			{
				return this._GroupId06;
			}
			set
			{
				if ((this._GroupId06 != value))
				{
					this.OnGroupId06Changing(value);
					this.SendPropertyChanging();
					this._GroupId06 = value;
					this.SendPropertyChanged("GroupId06");
					this.OnGroupId06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId07", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId07
		{
			get
			{
				return this._GroupId07;
			}
			set
			{
				if ((this._GroupId07 != value))
				{
					this.OnGroupId07Changing(value);
					this.SendPropertyChanging();
					this._GroupId07 = value;
					this.SendPropertyChanged("GroupId07");
					this.OnGroupId07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId08", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId08
		{
			get
			{
				return this._GroupId08;
			}
			set
			{
				if ((this._GroupId08 != value))
				{
					this.OnGroupId08Changing(value);
					this.SendPropertyChanging();
					this._GroupId08 = value;
					this.SendPropertyChanged("GroupId08");
					this.OnGroupId08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId09", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId09
		{
			get
			{
				return this._GroupId09;
			}
			set
			{
				if ((this._GroupId09 != value))
				{
					this.OnGroupId09Changing(value);
					this.SendPropertyChanging();
					this._GroupId09 = value;
					this.SendPropertyChanged("GroupId09");
					this.OnGroupId09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId10", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId10
		{
			get
			{
				return this._GroupId10;
			}
			set
			{
				if ((this._GroupId10 != value))
				{
					this.OnGroupId10Changing(value);
					this.SendPropertyChanging();
					this._GroupId10 = value;
					this.SendPropertyChanged("GroupId10");
					this.OnGroupId10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId11", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId11
		{
			get
			{
				return this._GroupId11;
			}
			set
			{
				if ((this._GroupId11 != value))
				{
					this.OnGroupId11Changing(value);
					this.SendPropertyChanging();
					this._GroupId11 = value;
					this.SendPropertyChanged("GroupId11");
					this.OnGroupId11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId12", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId12
		{
			get
			{
				return this._GroupId12;
			}
			set
			{
				if ((this._GroupId12 != value))
				{
					this.OnGroupId12Changing(value);
					this.SendPropertyChanging();
					this._GroupId12 = value;
					this.SendPropertyChanged("GroupId12");
					this.OnGroupId12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId13", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId13
		{
			get
			{
				return this._GroupId13;
			}
			set
			{
				if ((this._GroupId13 != value))
				{
					this.OnGroupId13Changing(value);
					this.SendPropertyChanging();
					this._GroupId13 = value;
					this.SendPropertyChanged("GroupId13");
					this.OnGroupId13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId14", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId14
		{
			get
			{
				return this._GroupId14;
			}
			set
			{
				if ((this._GroupId14 != value))
				{
					this.OnGroupId14Changing(value);
					this.SendPropertyChanging();
					this._GroupId14 = value;
					this.SendPropertyChanged("GroupId14");
					this.OnGroupId14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId15", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId15
		{
			get
			{
				return this._GroupId15;
			}
			set
			{
				if ((this._GroupId15 != value))
				{
					this.OnGroupId15Changing(value);
					this.SendPropertyChanging();
					this._GroupId15 = value;
					this.SendPropertyChanged("GroupId15");
					this.OnGroupId15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId16", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId16
		{
			get
			{
				return this._GroupId16;
			}
			set
			{
				if ((this._GroupId16 != value))
				{
					this.OnGroupId16Changing(value);
					this.SendPropertyChanging();
					this._GroupId16 = value;
					this.SendPropertyChanged("GroupId16");
					this.OnGroupId16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId17", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId17
		{
			get
			{
				return this._GroupId17;
			}
			set
			{
				if ((this._GroupId17 != value))
				{
					this.OnGroupId17Changing(value);
					this.SendPropertyChanging();
					this._GroupId17 = value;
					this.SendPropertyChanged("GroupId17");
					this.OnGroupId17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId18", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId18
		{
			get
			{
				return this._GroupId18;
			}
			set
			{
				if ((this._GroupId18 != value))
				{
					this.OnGroupId18Changing(value);
					this.SendPropertyChanging();
					this._GroupId18 = value;
					this.SendPropertyChanged("GroupId18");
					this.OnGroupId18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId19", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId19
		{
			get
			{
				return this._GroupId19;
			}
			set
			{
				if ((this._GroupId19 != value))
				{
					this.OnGroupId19Changing(value);
					this.SendPropertyChanging();
					this._GroupId19 = value;
					this.SendPropertyChanged("GroupId19");
					this.OnGroupId19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId20", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId20
		{
			get
			{
				return this._GroupId20;
			}
			set
			{
				if ((this._GroupId20 != value))
				{
					this.OnGroupId20Changing(value);
					this.SendPropertyChanging();
					this._GroupId20 = value;
					this.SendPropertyChanged("GroupId20");
					this.OnGroupId20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId21", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId21
		{
			get
			{
				return this._GroupId21;
			}
			set
			{
				if ((this._GroupId21 != value))
				{
					this.OnGroupId21Changing(value);
					this.SendPropertyChanging();
					this._GroupId21 = value;
					this.SendPropertyChanged("GroupId21");
					this.OnGroupId21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId22", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId22
		{
			get
			{
				return this._GroupId22;
			}
			set
			{
				if ((this._GroupId22 != value))
				{
					this.OnGroupId22Changing(value);
					this.SendPropertyChanging();
					this._GroupId22 = value;
					this.SendPropertyChanged("GroupId22");
					this.OnGroupId22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId23", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId23
		{
			get
			{
				return this._GroupId23;
			}
			set
			{
				if ((this._GroupId23 != value))
				{
					this.OnGroupId23Changing(value);
					this.SendPropertyChanging();
					this._GroupId23 = value;
					this.SendPropertyChanged("GroupId23");
					this.OnGroupId23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId24", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId24
		{
			get
			{
				return this._GroupId24;
			}
			set
			{
				if ((this._GroupId24 != value))
				{
					this.OnGroupId24Changing(value);
					this.SendPropertyChanging();
					this._GroupId24 = value;
					this.SendPropertyChanged("GroupId24");
					this.OnGroupId24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId25", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId25
		{
			get
			{
				return this._GroupId25;
			}
			set
			{
				if ((this._GroupId25 != value))
				{
					this.OnGroupId25Changing(value);
					this.SendPropertyChanging();
					this._GroupId25 = value;
					this.SendPropertyChanged("GroupId25");
					this.OnGroupId25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId26", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId26
		{
			get
			{
				return this._GroupId26;
			}
			set
			{
				if ((this._GroupId26 != value))
				{
					this.OnGroupId26Changing(value);
					this.SendPropertyChanging();
					this._GroupId26 = value;
					this.SendPropertyChanged("GroupId26");
					this.OnGroupId26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId27", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId27
		{
			get
			{
				return this._GroupId27;
			}
			set
			{
				if ((this._GroupId27 != value))
				{
					this.OnGroupId27Changing(value);
					this.SendPropertyChanging();
					this._GroupId27 = value;
					this.SendPropertyChanged("GroupId27");
					this.OnGroupId27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId28", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId28
		{
			get
			{
				return this._GroupId28;
			}
			set
			{
				if ((this._GroupId28 != value))
				{
					this.OnGroupId28Changing(value);
					this.SendPropertyChanging();
					this._GroupId28 = value;
					this.SendPropertyChanged("GroupId28");
					this.OnGroupId28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId29", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId29
		{
			get
			{
				return this._GroupId29;
			}
			set
			{
				if ((this._GroupId29 != value))
				{
					this.OnGroupId29Changing(value);
					this.SendPropertyChanging();
					this._GroupId29 = value;
					this.SendPropertyChanged("GroupId29");
					this.OnGroupId29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId30", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId30
		{
			get
			{
				return this._GroupId30;
			}
			set
			{
				if ((this._GroupId30 != value))
				{
					this.OnGroupId30Changing(value);
					this.SendPropertyChanging();
					this._GroupId30 = value;
					this.SendPropertyChanged("GroupId30");
					this.OnGroupId30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId31", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId31
		{
			get
			{
				return this._GroupId31;
			}
			set
			{
				if ((this._GroupId31 != value))
				{
					this.OnGroupId31Changing(value);
					this.SendPropertyChanging();
					this._GroupId31 = value;
					this.SendPropertyChanged("GroupId31");
					this.OnGroupId31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId32", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId32
		{
			get
			{
				return this._GroupId32;
			}
			set
			{
				if ((this._GroupId32 != value))
				{
					this.OnGroupId32Changing(value);
					this.SendPropertyChanging();
					this._GroupId32 = value;
					this.SendPropertyChanged("GroupId32");
					this.OnGroupId32Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId33", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId33
		{
			get
			{
				return this._GroupId33;
			}
			set
			{
				if ((this._GroupId33 != value))
				{
					this.OnGroupId33Changing(value);
					this.SendPropertyChanging();
					this._GroupId33 = value;
					this.SendPropertyChanged("GroupId33");
					this.OnGroupId33Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId34", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId34
		{
			get
			{
				return this._GroupId34;
			}
			set
			{
				if ((this._GroupId34 != value))
				{
					this.OnGroupId34Changing(value);
					this.SendPropertyChanging();
					this._GroupId34 = value;
					this.SendPropertyChanged("GroupId34");
					this.OnGroupId34Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId35", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId35
		{
			get
			{
				return this._GroupId35;
			}
			set
			{
				if ((this._GroupId35 != value))
				{
					this.OnGroupId35Changing(value);
					this.SendPropertyChanging();
					this._GroupId35 = value;
					this.SendPropertyChanged("GroupId35");
					this.OnGroupId35Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId36", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId36
		{
			get
			{
				return this._GroupId36;
			}
			set
			{
				if ((this._GroupId36 != value))
				{
					this.OnGroupId36Changing(value);
					this.SendPropertyChanging();
					this._GroupId36 = value;
					this.SendPropertyChanged("GroupId36");
					this.OnGroupId36Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId37", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId37
		{
			get
			{
				return this._GroupId37;
			}
			set
			{
				if ((this._GroupId37 != value))
				{
					this.OnGroupId37Changing(value);
					this.SendPropertyChanging();
					this._GroupId37 = value;
					this.SendPropertyChanged("GroupId37");
					this.OnGroupId37Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId38", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId38
		{
			get
			{
				return this._GroupId38;
			}
			set
			{
				if ((this._GroupId38 != value))
				{
					this.OnGroupId38Changing(value);
					this.SendPropertyChanging();
					this._GroupId38 = value;
					this.SendPropertyChanged("GroupId38");
					this.OnGroupId38Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId39", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId39
		{
			get
			{
				return this._GroupId39;
			}
			set
			{
				if ((this._GroupId39 != value))
				{
					this.OnGroupId39Changing(value);
					this.SendPropertyChanging();
					this._GroupId39 = value;
					this.SendPropertyChanged("GroupId39");
					this.OnGroupId39Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId40", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId40
		{
			get
			{
				return this._GroupId40;
			}
			set
			{
				if ((this._GroupId40 != value))
				{
					this.OnGroupId40Changing(value);
					this.SendPropertyChanging();
					this._GroupId40 = value;
					this.SendPropertyChanged("GroupId40");
					this.OnGroupId40Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId41", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId41
		{
			get
			{
				return this._GroupId41;
			}
			set
			{
				if ((this._GroupId41 != value))
				{
					this.OnGroupId41Changing(value);
					this.SendPropertyChanging();
					this._GroupId41 = value;
					this.SendPropertyChanged("GroupId41");
					this.OnGroupId41Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId42", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId42
		{
			get
			{
				return this._GroupId42;
			}
			set
			{
				if ((this._GroupId42 != value))
				{
					this.OnGroupId42Changing(value);
					this.SendPropertyChanging();
					this._GroupId42 = value;
					this.SendPropertyChanged("GroupId42");
					this.OnGroupId42Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId43", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId43
		{
			get
			{
				return this._GroupId43;
			}
			set
			{
				if ((this._GroupId43 != value))
				{
					this.OnGroupId43Changing(value);
					this.SendPropertyChanging();
					this._GroupId43 = value;
					this.SendPropertyChanged("GroupId43");
					this.OnGroupId43Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId44", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId44
		{
			get
			{
				return this._GroupId44;
			}
			set
			{
				if ((this._GroupId44 != value))
				{
					this.OnGroupId44Changing(value);
					this.SendPropertyChanging();
					this._GroupId44 = value;
					this.SendPropertyChanged("GroupId44");
					this.OnGroupId44Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId45", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId45
		{
			get
			{
				return this._GroupId45;
			}
			set
			{
				if ((this._GroupId45 != value))
				{
					this.OnGroupId45Changing(value);
					this.SendPropertyChanging();
					this._GroupId45 = value;
					this.SendPropertyChanged("GroupId45");
					this.OnGroupId45Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId46", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId46
		{
			get
			{
				return this._GroupId46;
			}
			set
			{
				if ((this._GroupId46 != value))
				{
					this.OnGroupId46Changing(value);
					this.SendPropertyChanging();
					this._GroupId46 = value;
					this.SendPropertyChanged("GroupId46");
					this.OnGroupId46Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId47", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId47
		{
			get
			{
				return this._GroupId47;
			}
			set
			{
				if ((this._GroupId47 != value))
				{
					this.OnGroupId47Changing(value);
					this.SendPropertyChanging();
					this._GroupId47 = value;
					this.SendPropertyChanged("GroupId47");
					this.OnGroupId47Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId48", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId48
		{
			get
			{
				return this._GroupId48;
			}
			set
			{
				if ((this._GroupId48 != value))
				{
					this.OnGroupId48Changing(value);
					this.SendPropertyChanging();
					this._GroupId48 = value;
					this.SendPropertyChanged("GroupId48");
					this.OnGroupId48Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId49", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId49
		{
			get
			{
				return this._GroupId49;
			}
			set
			{
				if ((this._GroupId49 != value))
				{
					this.OnGroupId49Changing(value);
					this.SendPropertyChanging();
					this._GroupId49 = value;
					this.SendPropertyChanged("GroupId49");
					this.OnGroupId49Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId50", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GroupId50
		{
			get
			{
				return this._GroupId50;
			}
			set
			{
				if ((this._GroupId50 != value))
				{
					this.OnGroupId50Changing(value);
					this.SendPropertyChanging();
					this._GroupId50 = value;
					this.SendPropertyChanged("GroupId50");
					this.OnGroupId50Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogicalDelete", DbType="Bit NOT NULL")]
		public bool IsLogicalDelete
		{
			get
			{
				return this._IsLogicalDelete;
			}
			set
			{
				if ((this._IsLogicalDelete != value))
				{
					this.OnIsLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsLogicalDelete = value;
					this.SendPropertyChanged("IsLogicalDelete");
					this.OnIsLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this.OnCreateUserChanging(value);
					this.SendPropertyChanging();
					this._CreateUser = value;
					this.SendPropertyChanged("CreateUser");
					this.OnCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeleteUser
		{
			get
			{
				return this._DeleteUser;
			}
			set
			{
				if ((this._DeleteUser != value))
				{
					this.OnDeleteUserChanging(value);
					this.SendPropertyChanging();
					this._DeleteUser = value;
					this.SendPropertyChanged("DeleteUser");
					this.OnDeleteUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserGroupTable_GroupTable", Storage="_GroupTables", ThisKey="GroupId01", OtherKey="GroupId")]
		public EntitySet<GroupTable> GroupTables
		{
			get
			{
				return this._GroupTables;
			}
			set
			{
				this._GroupTables.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTable_UserGroupTable", Storage="_UserTable", ThisKey="UserId", OtherKey="Id", IsForeignKey=true)]
		public UserTable UserTable
		{
			get
			{
				return this._UserTable.Entity;
			}
			set
			{
				UserTable previousValue = this._UserTable.Entity;
				if (((previousValue != value) 
							|| (this._UserTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserTable.Entity = null;
						previousValue.UserGroupTables.Remove(this);
					}
					this._UserTable.Entity = value;
					if ((value != null))
					{
						value.UserGroupTables.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(System.Guid);
					}
					this.SendPropertyChanged("UserTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GroupTables(GroupTable entity)
		{
			this.SendPropertyChanging();
			entity.UserGroupTable = this;
		}
		
		private void detach_GroupTables(GroupTable entity)
		{
			this.SendPropertyChanging();
			entity.UserGroupTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TargetDataTable")]
	public partial class TargetDataTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private int _Mode;
		
		private string _Tags;
		
		private System.Nullable<System.DateTime> _OccurrenceDateTime;
		
		private string _WhatAttribute;
		
		private System.Nullable<System.DateTime> _WhenAttribute;
		
		private string _WhyAttribute;
		
		private System.Guid _WhoAttribute;
		
		private string _WhereAttribute;
		
		private string _WhomAttribute;
		
		private string _HowAttribute;
		
		private string _HowMuchAttribute;
		
		private string _HowManyAttribute;
		
		private string _GroupNames;
		
		private bool _IsLogicalDelete;
		
		private System.Nullable<System.Guid> _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.Guid> _UpdateUser;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.Guid> _DeleteUser;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private EntityRef<UserTargetDataTable> _UserTargetDataTable;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnModeChanging(int value);
    partial void OnModeChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnOccurrenceDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnOccurrenceDateTimeChanged();
    partial void OnWhatAttributeChanging(string value);
    partial void OnWhatAttributeChanged();
    partial void OnWhenAttributeChanging(System.Nullable<System.DateTime> value);
    partial void OnWhenAttributeChanged();
    partial void OnWhyAttributeChanging(string value);
    partial void OnWhyAttributeChanged();
    partial void OnWhoAttributeChanging(System.Guid value);
    partial void OnWhoAttributeChanged();
    partial void OnWhereAttributeChanging(string value);
    partial void OnWhereAttributeChanged();
    partial void OnWhomAttributeChanging(string value);
    partial void OnWhomAttributeChanged();
    partial void OnHowAttributeChanging(string value);
    partial void OnHowAttributeChanged();
    partial void OnHowMuchAttributeChanging(string value);
    partial void OnHowMuchAttributeChanged();
    partial void OnHowManyAttributeChanging(string value);
    partial void OnHowManyAttributeChanged();
    partial void OnGroupNamesChanging(string value);
    partial void OnGroupNamesChanged();
    partial void OnIsLogicalDeleteChanging(bool value);
    partial void OnIsLogicalDeleteChanged();
    partial void OnCreateUserChanging(System.Nullable<System.Guid> value);
    partial void OnCreateUserChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateUserChanging(System.Nullable<System.Guid> value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeleteUserChanging(System.Nullable<System.Guid> value);
    partial void OnDeleteUserChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    #endregion
		
		public TargetDataTable()
		{
			this._UserTargetDataTable = default(EntityRef<UserTargetDataTable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._UserTargetDataTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="Int NOT NULL")]
		public int Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this.OnModeChanging(value);
					this.SendPropertyChanging();
					this._Mode = value;
					this.SendPropertyChanged("Mode");
					this.OnModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(MAX)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OccurrenceDateTime", DbType="DateTime2")]
		public System.Nullable<System.DateTime> OccurrenceDateTime
		{
			get
			{
				return this._OccurrenceDateTime;
			}
			set
			{
				if ((this._OccurrenceDateTime != value))
				{
					this.OnOccurrenceDateTimeChanging(value);
					this.SendPropertyChanging();
					this._OccurrenceDateTime = value;
					this.SendPropertyChanged("OccurrenceDateTime");
					this.OnOccurrenceDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhatAttribute", DbType="NVarChar(MAX)")]
		public string WhatAttribute
		{
			get
			{
				return this._WhatAttribute;
			}
			set
			{
				if ((this._WhatAttribute != value))
				{
					this.OnWhatAttributeChanging(value);
					this.SendPropertyChanging();
					this._WhatAttribute = value;
					this.SendPropertyChanged("WhatAttribute");
					this.OnWhatAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhenAttribute", DbType="DateTime2")]
		public System.Nullable<System.DateTime> WhenAttribute
		{
			get
			{
				return this._WhenAttribute;
			}
			set
			{
				if ((this._WhenAttribute != value))
				{
					this.OnWhenAttributeChanging(value);
					this.SendPropertyChanging();
					this._WhenAttribute = value;
					this.SendPropertyChanged("WhenAttribute");
					this.OnWhenAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhyAttribute", DbType="NVarChar(MAX)")]
		public string WhyAttribute
		{
			get
			{
				return this._WhyAttribute;
			}
			set
			{
				if ((this._WhyAttribute != value))
				{
					this.OnWhyAttributeChanging(value);
					this.SendPropertyChanging();
					this._WhyAttribute = value;
					this.SendPropertyChanged("WhyAttribute");
					this.OnWhyAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhoAttribute", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid WhoAttribute
		{
			get
			{
				return this._WhoAttribute;
			}
			set
			{
				if ((this._WhoAttribute != value))
				{
					this.OnWhoAttributeChanging(value);
					this.SendPropertyChanging();
					this._WhoAttribute = value;
					this.SendPropertyChanged("WhoAttribute");
					this.OnWhoAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhereAttribute", DbType="NVarChar(MAX)")]
		public string WhereAttribute
		{
			get
			{
				return this._WhereAttribute;
			}
			set
			{
				if ((this._WhereAttribute != value))
				{
					this.OnWhereAttributeChanging(value);
					this.SendPropertyChanging();
					this._WhereAttribute = value;
					this.SendPropertyChanged("WhereAttribute");
					this.OnWhereAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhomAttribute", DbType="NVarChar(MAX)")]
		public string WhomAttribute
		{
			get
			{
				return this._WhomAttribute;
			}
			set
			{
				if ((this._WhomAttribute != value))
				{
					this.OnWhomAttributeChanging(value);
					this.SendPropertyChanging();
					this._WhomAttribute = value;
					this.SendPropertyChanged("WhomAttribute");
					this.OnWhomAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HowAttribute", DbType="NVarChar(MAX)")]
		public string HowAttribute
		{
			get
			{
				return this._HowAttribute;
			}
			set
			{
				if ((this._HowAttribute != value))
				{
					this.OnHowAttributeChanging(value);
					this.SendPropertyChanging();
					this._HowAttribute = value;
					this.SendPropertyChanged("HowAttribute");
					this.OnHowAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HowMuchAttribute", DbType="NVarChar(MAX)")]
		public string HowMuchAttribute
		{
			get
			{
				return this._HowMuchAttribute;
			}
			set
			{
				if ((this._HowMuchAttribute != value))
				{
					this.OnHowMuchAttributeChanging(value);
					this.SendPropertyChanging();
					this._HowMuchAttribute = value;
					this.SendPropertyChanged("HowMuchAttribute");
					this.OnHowMuchAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HowManyAttribute", DbType="NVarChar(MAX)")]
		public string HowManyAttribute
		{
			get
			{
				return this._HowManyAttribute;
			}
			set
			{
				if ((this._HowManyAttribute != value))
				{
					this.OnHowManyAttributeChanging(value);
					this.SendPropertyChanging();
					this._HowManyAttribute = value;
					this.SendPropertyChanged("HowManyAttribute");
					this.OnHowManyAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupNames", DbType="NVarChar(MAX)")]
		public string GroupNames
		{
			get
			{
				return this._GroupNames;
			}
			set
			{
				if ((this._GroupNames != value))
				{
					this.OnGroupNamesChanging(value);
					this.SendPropertyChanging();
					this._GroupNames = value;
					this.SendPropertyChanged("GroupNames");
					this.OnGroupNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogicalDelete", DbType="Bit NOT NULL")]
		public bool IsLogicalDelete
		{
			get
			{
				return this._IsLogicalDelete;
			}
			set
			{
				if ((this._IsLogicalDelete != value))
				{
					this.OnIsLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsLogicalDelete = value;
					this.SendPropertyChanged("IsLogicalDelete");
					this.OnIsLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this.OnCreateUserChanging(value);
					this.SendPropertyChanging();
					this._CreateUser = value;
					this.SendPropertyChanged("CreateUser");
					this.OnCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeleteUser
		{
			get
			{
				return this._DeleteUser;
			}
			set
			{
				if ((this._DeleteUser != value))
				{
					this.OnDeleteUserChanging(value);
					this.SendPropertyChanging();
					this._DeleteUser = value;
					this.SendPropertyChanged("DeleteUser");
					this.OnDeleteUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTargetDataTable_TargetDataTable", Storage="_UserTargetDataTable", ThisKey="Id", OtherKey="TargetDataId", IsForeignKey=true)]
		public UserTargetDataTable UserTargetDataTable
		{
			get
			{
				return this._UserTargetDataTable.Entity;
			}
			set
			{
				UserTargetDataTable previousValue = this._UserTargetDataTable.Entity;
				if (((previousValue != value) 
							|| (this._UserTargetDataTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserTargetDataTable.Entity = null;
						previousValue.TargetDataTable.Remove(this);
					}
					this._UserTargetDataTable.Entity = value;
					if ((value != null))
					{
						value.TargetDataTable.Add(this);
						this._Id = value.TargetDataId;
					}
					else
					{
						this._Id = default(System.Guid);
					}
					this.SendPropertyChanged("UserTargetDataTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTargetDataTable")]
	public partial class UserTargetDataTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserId;
		
		private System.Guid _TargetDataId;
		
		private bool _IsLogicalDelete;
		
		private System.Nullable<System.Guid> _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.Guid> _UpdateUser;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.Guid> _DeleteUser;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private EntitySet<TargetDataTable> _TargetDataTable;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnTargetDataIdChanging(System.Guid value);
    partial void OnTargetDataIdChanged();
    partial void OnIsLogicalDeleteChanging(bool value);
    partial void OnIsLogicalDeleteChanged();
    partial void OnCreateUserChanging(System.Nullable<System.Guid> value);
    partial void OnCreateUserChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateUserChanging(System.Nullable<System.Guid> value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeleteUserChanging(System.Nullable<System.Guid> value);
    partial void OnDeleteUserChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    #endregion
		
		public UserTargetDataTable()
		{
			this._TargetDataTable = new EntitySet<TargetDataTable>(new Action<TargetDataTable>(this.attach_TargetDataTable), new Action<TargetDataTable>(this.detach_TargetDataTable));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetDataId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TargetDataId
		{
			get
			{
				return this._TargetDataId;
			}
			set
			{
				if ((this._TargetDataId != value))
				{
					this.OnTargetDataIdChanging(value);
					this.SendPropertyChanging();
					this._TargetDataId = value;
					this.SendPropertyChanged("TargetDataId");
					this.OnTargetDataIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogicalDelete", DbType="Bit NOT NULL")]
		public bool IsLogicalDelete
		{
			get
			{
				return this._IsLogicalDelete;
			}
			set
			{
				if ((this._IsLogicalDelete != value))
				{
					this.OnIsLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsLogicalDelete = value;
					this.SendPropertyChanged("IsLogicalDelete");
					this.OnIsLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this.OnCreateUserChanging(value);
					this.SendPropertyChanging();
					this._CreateUser = value;
					this.SendPropertyChanged("CreateUser");
					this.OnCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteUser", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeleteUser
		{
			get
			{
				return this._DeleteUser;
			}
			set
			{
				if ((this._DeleteUser != value))
				{
					this.OnDeleteUserChanging(value);
					this.SendPropertyChanging();
					this._DeleteUser = value;
					this.SendPropertyChanged("DeleteUser");
					this.OnDeleteUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTargetDataTable_TargetDataTable", Storage="_TargetDataTable", ThisKey="TargetDataId", OtherKey="Id")]
		public EntitySet<TargetDataTable> TargetDataTable
		{
			get
			{
				return this._TargetDataTable;
			}
			set
			{
				this._TargetDataTable.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TargetDataTable(TargetDataTable entity)
		{
			this.SendPropertyChanging();
			entity.UserTargetDataTable = this;
		}
		
		private void detach_TargetDataTable(TargetDataTable entity)
		{
			this.SendPropertyChanging();
			entity.UserTargetDataTable = null;
		}
	}
}
#pragma warning restore 1591
